### ISSUE TITLE
brouter not selectable in osmand 4.1.9

### ISSUE THREAD

**Issue by IeP4nieF** [abrensch/brouter#383]
Hi,

I have installed osmand 4.1.9 and brouter 1.6.2, both from f-droid. I downloaded routing-datafiles and completed the setup in brouter. But brouter is not listed in osmand as routing-engine during profile-creation. According to https://github.com/abrensch/brouter/blob/master/misc/readmes/osmand/README.md I forceclosed osmand, but that did not help.

I think this is a bug. But I don't know, wether it is a bug in osmand or brouter.

best regards

**Comment by poutnikl** [comment]
I remember configuration of recent OSMand versions to use BRouter routing service is much more hidden than earlier. I had to dig deep until I found the way.

**Comment by abrensch** [comment]
There was a fix recently on their side ( https://github.com/osmandapp/OsmAnd/pull/13328 ) made by Victor after he passed by here ( https://github.com/abrensch/brouter/issues/374 )

As far as I remember, OsmAnd does not offer BRouter if it does no "see" the Connection during initialisiation.

**Comment by IeP4nieF** [comment]
Ok, thanks for the hint. I'll wait for the next osmand update and test again.

**Comment by Bubu** [comment]
I just merged OsmAnd 4.1.11 into f-droid (so it'll be available there ... sometime soon-ish). That should contain the above referenced fix.

**Comment by Bubu** [comment]
4.1.11 is available. It somehow took multiple restarts of osmand and switching the profile to a different navigation service and back again, but it works again now with brouter 1.6.3 :-).

**Comment by IeP4nieF** [comment]
Here I still can't choose brouter as profile. I swichted three times the profile and force closed osmand after. brouter is still not shown in the list auf chooseable routing profiles. I started brouter before. Are you sure, that it is working again? (osmand: 4.1.11 and brouter 1.6.3 from f-droid)

**Comment by FFMbyBicycle** [comment]
Did you try to choose Brouter at the first step while creating a new profile? I think in the past there was this option, now it has moved. You have to create a standard "Cycling" profile first (you won't see the Brouter which I have at my screenshot) and then switch to Brouter using the profile settings. If it doesn't appear there, something is broken.

![Screenshot_20220204-092612_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497561-68b0a008-6fd0-426f-806b-431087d1dabb.png)

![Screenshot_20220204-092641_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497563-92c0aede-93b3-442e-b7fe-87a53a70fbeb.png)

![Screenshot_20220204-092655_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497564-efef6b2a-cca5-47cd-aa36-93938502ac66.png)

![Screenshot_20220204-092704_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497568-a8ac668e-2ec1-4c31-9e2f-df9007c845bf.png)

![Screenshot_20220204-092709_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497570-e2cd0ec8-7ca3-4a91-9716-45192161adfa.png)

![Screenshot_20220204-092719_OsmAnd~](https://user-images.githubusercontent.com/74880272/152497571-c1d3a31c-3370-446a-935b-29ac4c8f044f.png)

**Comment by IeP4nieF** [comment]
@FFMbyBicycle: Thank you!

Now I can choose BRouter as "navigation type". I can also choose this navigation type during creation of a new profile. I don't know what was my problem, but now it works as expected. I also checked with another device (fresh installation).
